#!/usr/bin/env python3
"""Generate a Loon Microsoft-CN rule from domain-list-community @cn entries."""

from __future__ import annotations

import argparse
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path


SOURCE_ROOT = "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/"
ROOT_LIST = "microsoft"


def fetch_list(name: str, cache: dict[str, str]) -> str:
    if name in cache:
        return cache[name]

    encoded_name = urllib.parse.quote(name, safe="-_@.")
    url = SOURCE_ROOT + encoded_name
    request = urllib.request.Request(url, headers={"User-Agent": "lat3ncy-proxy-configs"})
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            cache[name] = response.read().decode("utf-8")
    except (urllib.error.URLError, TimeoutError) as exc:
        raise RuntimeError(f"failed to download {url}: {exc}") from exc
    return cache[name]


def collect_cn_rules(
    name: str,
    inherited_tags: frozenset[str],
    cache: dict[str, str],
    visited: set[tuple[str, frozenset[str]]],
    rules: set[str],
) -> None:
    visit_key = (name, inherited_tags)
    if visit_key in visited:
        return
    visited.add(visit_key)

    for number, raw_line in enumerate(fetch_list(name, cache).splitlines(), start=1):
        content = raw_line.split("#", 1)[0].strip()
        if not content:
            continue

        parts = content.split()
        entry = parts[0]
        tags = inherited_tags | frozenset(part[1:].lower() for part in parts[1:] if part.startswith("@"))

        if entry.startswith("include:"):
            collect_cn_rules(entry.removeprefix("include:"), tags, cache, visited, rules)
            continue
        if "cn" not in tags:
            continue

        if entry.startswith("full:"):
            rule = "DOMAIN," + entry.removeprefix("full:")
        elif entry.startswith("keyword:"):
            rule = "DOMAIN-KEYWORD," + entry.removeprefix("keyword:")
        elif entry.startswith("regexp:"):
            raise RuntimeError(f"unsupported @cn regexp in {name}:{number}: {entry}")
        else:
            rule = "DOMAIN-SUFFIX," + entry.removeprefix("domain:")
        rules.add(rule)


def render() -> str:
    rules: set[str] = set()
    collect_cn_rules(ROOT_LIST, frozenset(), {}, set(), rules)
    ordered = sorted(rules, key=lambda value: (value.split(",", 1)[1], value))
    header = [
        "# Microsoft China direct rules for Loon",
        "# Generated by scripts/generate_microsoft_cn.py",
        f"# Source: {SOURCE_ROOT}{ROOT_LIST}",
        "# Includes recursively resolved; only entries tagged @cn are retained.",
        "",
    ]
    return "\n".join(header + ordered) + "\n"


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    default_output = repo_root / "loon" / "rules" / "microsoft-cn.list"
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=default_output)
    parser.add_argument("--check", action="store_true", help="compare generated content without writing")
    args = parser.parse_args()

    generated = render()
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current != generated:
            print(f"OUTDATED: {args.output}", file=sys.stderr)
            return 1
        print(f"PASS: {args.output} matches current domain-list-community @cn entries")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8", newline="\n")
    print(f"WROTE: {args.output} ({generated.count(chr(10)) - 5} rules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
